import { SiteHeader } from "@/components/SiteHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { trpc } from "@/lib/trpc";
import { Archive, ArrowRight, Box, CheckCircle2, Clock3, PackageOpen, PlusCircle, ReceiptText, Store, Tag } from "lucide-react";
import { Link } from "wouter";

const orderStatus = { placed: "已创建", confirmed: "待交接", completed: "已完成", cancelled: "已取消" } as const;
const listingStatus = { active: "展示中", reserved: "已被预留", archived: "已下架" } as const;
const listingTone = { active: "bg-emerald-50 text-emerald-700", reserved: "bg-amber-50 text-amber-700", archived: "bg-muted text-muted-foreground" } as const;

function dateLabel(value: Date | string) {
  return new Date(value).toLocaleDateString("zh-CN", { month: "numeric", day: "numeric" });
}

export default function Profile() {
  const { user, loading } = useAuth();
  const profile = trpc.profile.mine.useQuery(undefined, { enabled: Boolean(user) });

  if (loading) return <div className="min-h-screen bg-background" />;
  if (!user) return <div className="min-h-screen bg-background"><SiteHeader /><main className="container py-16"><section className="max-w-xl rounded-[1.5rem] border border-border bg-card p-8"><Store className="size-6 text-primary" /><h1 className="mt-5 font-display text-3xl font-bold">登录后管理你的校园流转</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">个人中心只展示当前账户的模拟订单和已发布闲置物品。登录不会公开其他用户的订单或发布记录。</p><Button className="mt-6 rounded-xl" onClick={() => startLogin()}>前往登录</Button></section></main></div>;

  const data = profile.data;
  const listings = data?.listings ?? [];
  const orders = data?.orders ?? [];
  const summary = data?.summary;
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container py-9 sm:py-12"><section className="overflow-hidden rounded-[1.75rem] border border-border bg-[linear-gradient(115deg,#321b49_0%,#4d2b62_58%,#6d4678_100%)] p-7 text-primary-foreground shadow-[0_22px_54px_-32px_rgba(45,33,60,0.85)] sm:p-10"><div className="flex flex-col gap-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold tracking-[0.15em] text-[#d8c8e7]">MY CAMPUS FLOW</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-0.06em] sm:text-5xl">你好，{user.name ?? "校园同学"}。</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#eadff1]">这里把你的模拟购买与发布状态收在同一处。所有信息只由当前 OAuth 会话的用户 ID 查询，用于完整演示校园交易从发现到流转的业务链路。</p></div><Link href="/goods" className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-primary transition-transform duration-200 hover:scale-[1.02]"><PlusCircle className="size-4" />继续发现好物</Link></div></section>

  <section className="mt-7 grid gap-4 md:grid-cols-4"><article className="rounded-2xl border border-border bg-card p-5"><ReceiptText className="size-5 text-primary" /><p className="mt-5 text-xs font-semibold tracking-[0.12em] text-muted-foreground">模拟订单</p><p className="mt-1 font-mono text-3xl font-bold">{summary?.orderCount ?? 0}</p></article><article className="rounded-2xl border border-border bg-card p-5"><Store className="size-5 text-primary" /><p className="mt-5 text-xs font-semibold tracking-[0.12em] text-muted-foreground">正在展示</p><p className="mt-1 font-mono text-3xl font-bold">{summary?.activeListings ?? 0}</p></article><article className="rounded-2xl border border-border bg-card p-5"><Clock3 className="size-5 text-amber-600" /><p className="mt-5 text-xs font-semibold tracking-[0.12em] text-muted-foreground">等待交接</p><p className="mt-1 font-mono text-3xl font-bold">{summary?.reservedListings ?? 0}</p></article><article className="rounded-2xl border border-border bg-card p-5"><Archive className="size-5 text-muted-foreground" /><p className="mt-5 text-xs font-semibold tracking-[0.12em] text-muted-foreground">已下架</p><p className="mt-1 font-mono text-3xl font-bold">{summary?.archivedListings ?? 0}</p></article></section>

  <section className="mt-8 grid gap-6 lg:grid-cols-[0.9fr_1.1fr]"><article className="rounded-[1.5rem] border border-border bg-card p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-[0.14em] text-primary">ORDER TIMELINE</p><h2 className="mt-2 font-display text-2xl font-bold tracking-[-0.04em]">我的模拟订单轨迹</h2></div><ReceiptText className="size-5 text-primary" /></div>{profile.isLoading ? <div className="mt-8 h-28 animate-pulse rounded-xl bg-secondary" /> : orders.length === 0 ? <div className="mt-7 rounded-2xl border border-dashed border-border bg-secondary/25 p-6 text-center"><PackageOpen className="mx-auto size-7 text-primary" /><h3 className="mt-4 font-display text-xl font-bold">还没有模拟订单</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">从商品详情创建一笔模拟订单后，创建时间、订单状态和物品快照会在这里形成可讲解的业务轨迹。</p><Link href="/goods" className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-primary hover:underline">去创建第一笔订单 <ArrowRight className="size-4" /></Link></div> : <ol className="mt-7 space-y-5">{orders.map((order, index) => <li key={order.id} className="relative flex gap-4"><span className="mt-1 grid size-7 shrink-0 place-items-center rounded-full bg-primary text-primary-foreground"><CheckCircle2 className="size-4" /></span>{index < orders.length - 1 ? <span className="absolute left-[13px] top-9 h-[calc(100%+4px)] border-l border-dashed border-primary/30" /> : null}<div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-semibold text-foreground">{order.orderCode}</p><Badge variant="secondary" className="font-normal">{orderStatus[order.status]}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{order.items.map(item => item.titleSnapshot).join("、")}</p><p className="mt-2 text-xs text-muted-foreground">{dateLabel(order.createdAt)} 创建 · 演示订单仅归当前账户可见</p></div></li>)}</ol>}</article>
  <article className="rounded-[1.5rem] border border-border bg-card p-6 sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold tracking-[0.14em] text-primary">MY LISTINGS</p><h2 className="mt-2 font-display text-2xl font-bold tracking-[-0.04em]">已发布的闲置物品</h2><p className="mt-2 text-sm text-muted-foreground">仅展示 `sellerUserId` 等于当前会话用户的演示商品。</p></div><Tag className="size-5 text-primary" /></div>{profile.isLoading ? <div className="mt-7 grid gap-3"><div className="h-24 animate-pulse rounded-xl bg-secondary" /><div className="h-24 animate-pulse rounded-xl bg-secondary" /></div> : listings.length === 0 ? <div className="mt-7 rounded-2xl border border-dashed border-border bg-secondary/25 p-6"><Box className="size-7 text-primary" /><h3 className="mt-4 font-display text-xl font-bold">还没有发布记录</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">当前账户没有已发布的演示商品。管理员账户会看到预置目录的发布状态，普通账户会保持隔离的空态。</p></div> : <div className="mt-7 space-y-3">{listings.map(item => <Link key={item.product.id} href={`/goods/${item.product.id}`} className="flex gap-3 rounded-2xl border border-border bg-secondary/15 p-3 transition-colors hover:bg-secondary/35"><img src={item.images[0]?.url} alt={item.images[0]?.altText ?? item.product.title} className="size-[74px] shrink-0 rounded-xl object-cover" /><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="line-clamp-1 font-semibold text-foreground">{item.product.title}</p><Badge className={`shrink-0 border-0 ${listingTone[item.product.status]}`}>{listingStatus[item.product.status]}</Badge></div><p className="mt-2 text-xs text-muted-foreground">{item.category.name} · 更新于 {dateLabel(item.product.updatedAt)}</p><p className="mt-2 text-xs font-medium text-primary">点击查看商品详情 <ArrowRight className="inline size-3" /></p></div></Link>)}</div>}</article></section>
  </main></div>;
}
