import { SiteHeader } from "@/components/SiteHeader";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import { Bot, Database, FileSearch, KeyRound, Layers3, ShieldCheck } from "lucide-react";

const modules = [
  ["商品与订单", "公开商品发现 + 登录后模拟下单 + 仅本人可见的订单空间", ShieldCheck],
  ["RAG 知识库", "分块、语料级 TF-IDF、余弦检索、来源片段与低置信转人工", FileSearch],
  ["Agent 路由", "FastAPI + LangGraph + Chroma 公开路由，Node 网关执行商品/订单/工单工具", Bot],
  ["权限与审计", "OAuth 会话、管理员过程、所有者验证与追加式安全记录", KeyRound],
];

export default function ProjectGuide() {
  return <div className="min-h-screen bg-background"><SiteHeader /><main className="container py-10 sm:py-14"><section className="grid gap-6 rounded-[1.75rem] bg-primary p-7 text-primary-foreground shadow-[0_22px_54px_-32px_rgba(45,33,60,0.85)] lg:grid-cols-[1.3fr_0.7fr] lg:p-10"><div><p className="text-xs font-semibold tracking-[0.16em] text-[#d8c8e7]">PROJECT DOCUMENTATION</p><h1 className="mt-3 font-display text-4xl font-bold tracking-[-0.06em] sm:text-5xl">把可信边界，做成可演示的产品。</h1><p className="mt-5 max-w-2xl text-sm leading-7 text-[#eee5f4]">CampusMate 将校园二手交易的前台体验、模拟订单权限、RAG 客服与可复现评测组合为一套可讲清工程取舍的 AI 应用作品。</p></div><div className="rounded-2xl border border-white/15 bg-white/10 p-5"><p className="text-xs font-semibold tracking-[0.13em] text-[#ddcfeb]">DEMO DISCLOSURE</p><p className="mt-3 font-display text-2xl font-bold">所有商品、订单与规则均明确标注为演示。</p><p className="mt-3 text-sm leading-6 text-[#eee5f4]">公开 C2C 规则用于来源明确的改写，不构成校方政策、法律意见或真实售后承诺。</p></div></section>
  <section className="mt-10"><p className="text-xs font-semibold tracking-[0.15em] text-primary">SYSTEM FLOW</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-0.05em]">从页面到证据，再到可审计结果。</h2><div className="mt-6 grid gap-3 md:grid-cols-3 xl:grid-cols-6">{[["React", "学院编辑风前台"],["tRPC", "端到端类型契约"],["Express", "会话与工具边界"],["FastAPI", "Python Agent 网关"],["LangGraph + Chroma", "状态图与公开规则召回"],["MySQL + LLM", "审计数据与受控生成"]].map(([title, description], index) => <div key={title} className="relative rounded-2xl border border-border bg-card p-5"><span className="font-mono text-xs text-primary">0{index + 1}</span><p className="mt-5 font-display text-xl font-bold">{title}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{description}</p></div>)}</div></section>
  <section className="mt-12 grid gap-4 md:grid-cols-2">{modules.map(([title, description, Icon]) => { const ResolvedIcon = Icon as typeof Layers3; return <article key={title as string} className="rounded-[1.25rem] border border-border bg-card p-6"><ResolvedIcon className="size-5 text-primary" /><h3 className="mt-5 font-display text-2xl font-bold">{title as string}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{description as string}</p></article> })}</section>
  <section className="mt-12 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-xs font-semibold tracking-[0.15em] text-primary">INTERVIEW DEEP DIVE</p><h2 className="mt-2 font-display text-3xl font-bold tracking-[-0.05em]">面试官可以一直追问。</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">下面的问题对应实际代码中的路由、表结构、检索器、审计函数与测试，而不是只停留在功能描述。</p><Badge variant="secondary" className="mt-5 font-normal">41 项 TypeScript + 6 项 Python 自动化测试</Badge></div><Accordion type="single" collapsible className="rounded-[1.25rem] border border-border bg-card px-5"><AccordionItem value="rag"><AccordionTrigger>为什么检索低分时要拒答？</AccordionTrigger><AccordionContent>因为模型的流畅表达不能替代事实依据。CampusMate 的 Node 回退检索与 Chroma 检索都受阈值控制；Chroma 使用 BGE 中文预训练语义向量，若仍无足够证据，就明确提示知识库覆盖不足并转人工。</AccordionContent></AccordionItem><AccordionItem value="orders"><AccordionTrigger>订单隔离如何抵抗直接 API 调用？</AccordionTrigger><AccordionContent>服务端从 OAuth 会话获得当前用户，不接受客户端传入的用户 ID。订单详情额外检查订单所有者；跨账户访问被拒绝并追加审计。</AccordionContent></AccordionItem><AccordionItem value="workflow"><AccordionTrigger>为什么 Python Agent 不直接查询订单？</AccordionTrigger><AccordionContent>FastAPI/LangGraph 只接收公开问题并返回意图和规则证据，既不读取 Cookie，也不拥有订单数据库凭据。Node 网关完成 OAuth 验证后才执行商品、订单或工单工具，从而保持最小权限。</AccordionContent></AccordionItem><AccordionItem value="admin"><AccordionTrigger>为什么还要在服务端限制管理员？</AccordionTrigger><AccordionContent>前端隐藏只能改善体验。真正的角色门槛由 tRPC 的 adminProcedure 在服务端拦截；普通用户直连后台 API 也会收到 FORBIDDEN。</AccordionContent></AccordionItem><AccordionItem value="evaluation"><AccordionTrigger>评测指标为何可信？</AccordionTrigger><AccordionContent>固定案例、预期意图、预期结果和必需引用均存储在数据库。每次运行生成新的 evaluationRuns，面板从实际运行记录聚合百分比和延迟。</AccordionContent></AccordionItem></Accordion></section>
  </main></div>;
}
